name: Rust

on: [push]

jobs:
  build:
    name: Rust ${{ matrix.rust-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust-version: [1.33.0, beta, nightly]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust-version }}
    - uses: actions/checkout@v1
    - name: Check formatting
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
