name: rust

on: [push]

jobs:
  build:
    name: Rust ${{ matrix.rust-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust-version: [1.34.0, beta, nightly]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust-version }}

    - uses: actions/checkout@v1

    - name: Check formatting
      if: matrix.rust-version != 'nightly'
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check
    - name: Check formatting
      if: matrix.rust-version == 'nightly'
      continue-on-error: true
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check

    - name: Build
      if: matrix.rust-version != 'nightly'
      run: cargo build --all --verbose
    - name: Build
      if: matrix.rust-version == 'nightly'
      continue-on-error: true
      run: cargo build --all --verbose

    - name: Run tests
      if: matrix.rust-version != 'nightly'
      run: cargo test --all --verbose
    - name: Run tests
      if: matrix.rust-version == 'nightly'
      continue-on-error: true
      run: cargo test --all --verbose
